### ISSUE TITLE
GDPR challenges

### ISSUE THREAD

**Issue by dictvm** [devops-nrw/meetup-orga#1]
Challenges of the new EU data protection regulation for ops teams (security, accountability, right to be forgotten, etc)

**Comment by fhemberger** [comment]
Related: There will be a full day workshop in Dusseldorf as #btconf side event:
https://beyondtellerrand.com/events/duesseldorf-2018/side-events/data-protection

I'm participating.

**Comment by dictvm** [comment]
@fhemberger good to know, thank you!
