### ISSUE TITLE
How to make your own Kubernetes native Controller

### ISSUE THREAD

**Issue by opusmagnum** [devops-nrw/meetup-orga#4]
### Talk proposal

at the beginning, I thought about short and quick introduction to the topic with some code snippets as an example, about 5-10 mins (like a lightning talk). If we have more time, can show more details and maybe even a live demo.

Please comment, which controller-programming aspects would you like to know.

**Comment by dictvm** [comment]
@opusmagnum are you interested in giving this lecture at the upcoming [meetup](https://www.meetup.com/de-DE/devops-duesseldorf/events/254007215/)? If possible it would be awesome if you could make it into a talk of about 15-20 minutes + Q&A.

**Comment by opusmagnum** [comment]
@dictvm -- yes, I have already registered myself for the meetup and will prepare the talk. 15-20 minutes should be fine, then I can add few more details.
Thank you.

**Comment by dictvm** [comment]
@opusmagnum awesome. Could you provide me with a short abstract for the talk during this week?

**Comment by opusmagnum** [comment]
@dictvm sure, try to do my best (because of attending SRE EU 2018 conference).

**Comment by dictvm** [comment]
@opusmagnum I'll be there as well. Don't sweat it if you don't finde the time. See you there! :)
